# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c89e872cb9a5a3d6fc89642dce20a439"
name = "collection-studio"
application_url = "https://collectionstudio.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "bulk_operations/finish" ]
  uri = "/webhooks/bulk-operations"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app_subscriptions/update"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [ "https://collectionstudio.app/api/auth" ]

[privacy_compliance]
customer_deletion_url = "https://collectionstudio.app/webhooks/customers/redact"
customer_data_request_url = "https://collectionstudio.app/webhooks/customers/data_request"
shop_deletion_url = "https://collectionstudio.app/webhooks/shop/redact"
